[package]
name = "tree-sitter-ron"
version = "0.1.0"
edition = "2021"
description = "RON grammar for tree-sitter"
license = "MIT"

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter = "~0.25"

[build-dependencies]
cc = "1.0"
